# --- General settings ---
base_year: 2015
scenario: 'Basis'
database_host: "http://opendata.ffe.de:4000/"
dict_source: database
# Set the maximum number of cpu threads to be used. Logic:
#   If max_cpu_count exceeds the number of available threads OR
#   if max_cpu_count is under the negative of available threads OR
#   if max_cpu_count equals zero:
#       => use all available threads.
#   ElseIf max_cpu_count is above zero but below the number of available threads:
#       => use max_cpu_count
#   ElseIf max_cpu_count is below zero but above the negative of available threads:
#       => lower the available threads (so: all available threads + max_cpu_count)
#
#   Example: If max_cpu_count == -1, and the computer has 8 available threads, 7 = 8 + (-1) are being used.
max_cpu_count: -1
use_nuts_2016: True

# --- Input data config ---

# 1. Dimensionless -
elc_cons_HH_total:
    source: database
    filename: elc_consumption_HH_total.csv
    table_id: 2

elc_cons_HH_by_size:
    source: database
    filename: elc_consumption_by_HH_size.csv
    table_id: 13

heat_consumption_HH:
    source: local
    filename: heat_consumption_households.csv
    
gas_consumption_HH:
    source: database
    filename: gas_consumption_households.csv
    table_id: 35

# 2. Spatial
population:
    source: database
    filename: population.csv
    table_id: 1

demographic_trend:
    source: database
    filename: demographic_trend.csv
    table_id: 48
    internal_id: 2

household_sizes:
    source: database
    filename: households.csv
    table_id: 14

income:
    source: database
    filename: income.csv
    table_id: 45
    internal_id: 2  # 1=sum of available income; 2=available income per capita

living_space:
    source: database
    filename: living_space.csv
    table_id: 12
    # If left empty or given value impossible (e.g. -1) -> do not filter.
    internal_id:
        0: -1   # building types. 1: 1FH, 2: 2FH, 3: MFH(3-6), 4: MFH(7-12), 5: MFH(>12)
        1: -1   # building vintage class (1 newest, 11: oldest)
        2: -1   # heating system or id_et: 9=Steinkohle; 10=Braunkohle; 11=Erdgas; 34=Heizoel; 35=Biomasse (fest); 68=Umgebungswaerme; 69=Solarwaerme; 71=Fernwaerme; 72=Elektrische Energie; 218=Biomasse (außer Holz, Biogas)
        3: -1   # non empty building. 0/False: building empty, 1/True: building not empty

percentage_EFH_MFH:
    source: database
    filename: percentage_EFH_MFH.csv
    table_id: 61


energy_balance_values:
    source: database
    filename: energy_balance_values.csv
    table_id: 59
    internal_id:
        0: -1  # line in balance sheet, e.g. 52=private households
        1: -1  # column in balance sheet, e.g. 29=power
    

elc_cons_HH_spatial:
    source: database
    filename: elc_consumption_HH_spatial.csv
    table_id: 4

stove_assumptions:
    source: local
    filename: stove_assumptions_nuts1.csv

hotwater_shares:
    source: local
    filename: hotwater_shares_nuts1.csv

heating_systems:
    source: local
    filename: heating_systems_nuts1.csv

heat_dem_bld: # heating demand of buildings
    source: database
    table_id: 47
    internal_id:
        0: -1   # building types. 1: 1FH, 2: RH, 3: MFH, 4: GMH
        1: -1   # building vintage class. 1: vor 1859; 2: 1860 bis 1918; 3: 1919 bis 1948; 4: 1949 bis 1957; 5: 1958 bis 1968; 6: 1969 bis 1978; 7: 1979 bis 1983; 8: 1984 bis 1994; 9: 1995 bis 2001; 10: 2002 bis 2009
        2: 1   # heating system. 1: Netto-Heizwärme, 2: Warmwasser (Nutzwärme), 3: Heizung, 4: Warmwasser (Wärmeerzeugung), 5: fossile Brennstoffe, 6: Holz/Biomasse, 7: Strom (inkl. Hilfsenergie), 8: Stromerzeugung, 9: Primärenergiebedarf (gesamt), 10: Primärenergiebedarf (nicht-erneuerbar)
        3: -1   # Variante. 1: Ist-Zustand, 2: Modernisierungspaket 1 (""konventionell""), 3: Modernisierungspaket 2 (""zukunftsweisend"")"

# 3. Temporal
elc_cons_HH_temporal:
    source: database
    table_id: 6

# 4. Spatiotemporal
slp_H0_1H:
    source: database
    table_id: 23
    freq: 1H

slp_H0_15min:
    source: database
    table_id: 24
    freq: 15T

slp_H0_1H_gas:
    source: database
    table_id: 28
    internal_id: 0   # 0=EFH, 1=MFH
    freq: 1H

ambient_T:
    source: database
    # table_id: 11=centroid of the region, 12=biggest settlement/area (village, town)
    table_id: 12
    internal_id: 1
    freq: 1H

solar_irradiation:
    source: database
    table_id: 17
    freq: 15T

elc_cons_HH_spatiotemporal:
    source: database
    table_id: 7
    freq: 1H
    
# --- Variable Type Configuration ---
dtypes:
    ags_lk: str
    id: int
    id_temporal: int
    id_spatial: int
    id_region_type: int
    id_region: int
    year_step: int
    year_weather: int
    internal_id: int
    values: str
    max: float
    min: float
    sum: float

# contains all table_id's of those tables with spatially high data on nuts 3 level
nuts3_tables: [1, 4, 5, 12, 14, 15, 16, 17, 18, 19, 20, 26, 27, 28, 29, 30, 31, 32, 33, 34, 39, 40, 41, 42, 43, 44, 45, 48, 49, 50, 55, 56, 57, 61]

# load table sectionwise:
load_sectionwise:
    spatial: []
    temporal: []
